spring:
  application:
    name: aac-backend
  profiles:
    active: local
  config:
    import:
      - config/jwt.yml
      - config/oidc.yml
      - config/openai.yml
  ai:
    openai:
      chat:
        options:
          model: gpt-4o
          temperature: 0.3
      embedding:
        options:
          model: text-embedding-3-small
cors:
  allowed-origins:
    - http://localhost:5173
    - http://127.0.0.1:5173
