spring:
  datasource:
    url: ${db.local.url}
    username: ${db.local.username}
    password: ${db.local.password}
    driver-class-name: ${db.local.driver-class-name}
  jpa:
    hibernate:
      ddl-auto: ${db.local.ddl-auto}
    show-sql: ${db.local.show-sql}
  h2:
    console:
      enabled: true
